name: PortageTextProcessing test suite

on: [push]

jobs:
  test-on-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: ["3.7", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Install Perl dependencies
      run: |
        sudo apt-get install -y libxml-twig-perl libxml-writer-perl libxml-xpath-perl xml-twig-tools libxml2-utils
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python 3 dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Run tests
      run: |
        source SETUP.bash && cd tests && ./run-all-tests.sh -show-logs
