name: PortestTextProcessing test suite

on: [push]

jobs:
  test-on-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install Python 3 dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Install Perl dependencies
      run: |
        sudo apt-get install -y libxml-twig-perl libxml-writer-perl libxml-xpath-perl
    - name: Run tests
      run: |
        source SETUP.bash && cd tests && ./run-all-tests.sh
